### ISSUE TITLE
LibHistoire issues linking events after clicking chain link

### ISSUE THREAD

**Issue by Sharlikran** [sirinsidiator/ESO-LibHistoire#1]
I apologize as I have mentioned I can not get users to give you information. The do not feel the desire to do so since they contacted me. They also for some reason do not see things the way you do and contact you first. I don't have any control over that.

[LibHistoire.zip](https://github.com/sirinsidiator/ESO-LibHistoire/files/6305835/LibHistoire.zip)

So the report simply is, they have to click the chain each and every day and after they do then LibHistoire sends the data to MM.  Next day same thing. I had one user get frustrated and deleted his LibHistoire saved vars file and start from scratch and said that fixed his issue.

I can only assume it is similar to https://github.com/ESOUIMods/AdvancedMemberTooltip/issues/1 in that at some point LibHistoire doesn't have something to reference to know how to resolve the events and link properly even after requesting a day of data.

Since I have no issues and I can't get the person to contact you I really can't provide details. I want to do something though because I just had another person post they are missing sales and I figure they probably have this ungodly large gap of more then 10 days of unlinked events, and no idea what is going on.

I know they don't know what is going on because this is their post
```
Hi...
I have a issue...apparently MM is not showing all guilds sales.
I put MM and ATT together and ATT is showing all my 3 trader guilds

Why this?
```
![image](https://user-images.githubusercontent.com/1912426/114601055-ec8ad800-9c49-11eb-9d12-610e0b3c86af.png)

**Comment by Chalinal** [comment]
[LibHistoire.zip](https://github.com/sirinsidiator/ESO-LibHistoire/files/6412803/LibHistoire.zip)

**Comment by Chalinal** [comment]
[LibDebugLogger.zip](https://github.com/sirinsidiator/ESO-LibHistoire/files/6412804/LibDebugLogger.zip)

**Comment by Sharlikran** [comment]
@sirinsidiator This user has a more severe situation

Unless there is a cloud service interfering here is what we did today

1. Request one day of data, click chain link
2. Repeat and click rescan until 10 days of data was obtained
3. Use the new MM commands to clean the database of any bad item links from the past versions of LH
```
/mm redesc
/mm clean
/mm dups
```
4. Open the MM window and click Refresh
5. Reload UI

blank sales bar in the LH GUI

![image](https://user-images.githubusercontent.com/1912426/116843279-54bb4280-ab94-11eb-917e-05a8c483b67b.png)

# Expected Result

The chain link should not be there after reloading the UI if we just completed a ten day scan.

**NOTE: The screen shot was before the ten day scan and ignore the erroneous time stamps**

**Comment by Sharlikran** [comment]
At this time I don't know if @Chalinal has an issue because of security or if LH has an issue but I can't reproduce what the user is experiencing with new files.

The user has an added program Webroot SecureAnywhere. I use windows 7. I have suggested to following because I have had various users do some of those and ESO stops crashing. It also resolves whatever odd issue with saved variables they report.

1) Disable Protected Folders
2) Disable Controlled Folder Access
3) Disable Ransomeware Protection 
4) Disable Windows Defender
5) Uninstall Avast or Kaspersky if you have either
6) Uninstall any cloud service like OneDrive, GoogleDrive, iDrive
7) Configure exceptions to give full read and write access to your MyDocuments folder so that games like ESO can store its own saved variables.

I suggested changing one thing at a time until LibHistoire functions correctly. Once it functions correctly at that point try to revert one change at a time to see the minimum configuration to protect your computer the way you want and still allow ESO to do what it is programmed to do.

**Comment by Sharlikran** [comment]
# Requested 2 days of data and clicked the chain link

![linked](https://user-images.githubusercontent.com/1912426/117024379-cb4c6300-acae-11eb-8ef4-febe2effe92e.jpg)

# Reload the UI and then the user had this

![unlinked](https://user-images.githubusercontent.com/1912426/117024538-efa83f80-acae-11eb-8d77-254cd90b9dcb.jpg)

# Thoughts

I can't reproduce the issue but I am not in a large guild. I have 4K events for three days of data. I can't tell if this is an issue with LibHistoire but there were a few revisions where new users data did not save. You fixed that but I thought I would report this anyway. 

I simply can not see how a bunch of added security programs will lock down the SavedVariables folder or the game such that once they reload the UI they get unusual results.

Chalinal explained to me that the 0 events is how it always is. It never shows xx hours of unlinked events. Never, not once they log in for the first time and not after a UI reload. Only after clicking the chain link does the tooltip change to green text.
