### ISSUE TITLE
I've changed my ESO id how do I relink my buy/sell history

### ISSUE THREAD

**Issue by molleafauss** [sirinsidiator/ESO-LibHistoire#2]
Hey, I've changed my ESO uid and now Master Merchant can't find my previous sales.
It's expected, but I'd like to understand if there's a simple way to relink past history.
Alternative is zapping the LibHistoire entirely and rescan it fully, but would be nice keeping the old data.

I was looking to go through the `LibHistorie.lua` in the saved variables dir and do some magic, but I'm lost when trying to understand how the data is organised, some guidance would be appreciated.

Thanks.

**Comment by sirinsidiator** [comment]
The data stored by LibHistoire is independent of your account(s). This is purely a problem with how Master Merchant stores data. You may be able to trigger a full rescan in Master Merchant to get previous sales back, but it's best you just ask the author how he'd approach that issue before doing that.
