### ISSUE TITLE
Event error

### ISSUE THREAD

**Issue by TrueMadMotion** [sirinsidiator/ESO-LibHistoire#3]
Will this cause a problem with MM?
**Event 2057924252 (2) needs to go somewhere between 2057922354 and 2057925484
|rstack traceback:
user:/AddOns/LibDebugLogger/LogHandler.lua:189: in function 'Log'
|caaaaaa<Locals> level = "W", config = [table:1]{originalTag = "LibHistoire", tag = "LibHistoire", enabled = T}, handled = T, message = "Event 2057924252 (2) needs to ...", shouldLogTraces = T </Locals>|r
(tail call): ?
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryCacheCategory.lua:732: in function 'GuildHistoryCacheCategory:SeparateReceivedEvents'
|caaaaaa<Locals> self = [table:2]{eventIndexLookupDirty = F, lastRequestTime = 1649417012, progressDirty = F, lastIndex = 507, guildId = 525912, progress = 0.55567715458276, waitForMore = 507, missingTime = 22736, key = "EU Megaserver/525912/3", category = 3}, events = [table:3]{}, eventsBefore = [table:4]{}, eventsAfter = [table:5]{}, lastEventId = 2057925484, firstEventId = 2057922354, eventId = 2057263044, i = 2, entry = [table:6]{valid = T}, eventId = 2057924252 </Locals>|r
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryCacheCategory.lua:607: in function 'GuildHistoryCacheCategory:ReceiveEvents'
|caaaaaa<Locals> self = [table:2], events = [table:3], hasReachedLastStoredEventId = F </Locals>|r
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryRequestManager.lua:62: in function '(anonymous)'
|caaaaaa<Locals> _ = 327726, guildId = 525912, category = 3, categoryCache = [table:2] </Locals>|r**

**Comment by sirinsidiator** [comment]
That's a warning, not an error. In my own experience it doesn't cause any problems, but there may potentially be some situations I don't know about where it can be problematic, which is why I log it.
