### ISSUE TITLE
item pulled down in history is not accurate for different types of potions.

### ISSUE THREAD

**Issue by johnbnstx** [sirinsidiator/ESO-LibHistoire#4]
If I look in mail I can click on the hyperlink of the item (potion) and see the type of potion sold. However, the history tab are shows the basic healing potion and not the actual potion that I crafted was sold.
That updates to Master Merchant that now holds the wrong data for the potion.

![image](https://github.com/sirinsidiator/ESO-LibHistoire/assets/43454462/857e4a16-043f-46cd-8728-264aa986e17c)

![image](https://github.com/sirinsidiator/ESO-LibHistoire/assets/43454462/59105c56-d5f2-4eea-b181-94b35acf2251)

In addition, it appears extracting history you have to sit there for a very long time. Is that because the data is going to be missing since I was not logged in? I had swapped between accounts and that took about an hour and half as the guild on this alt account is not on my main account.
![image](https://github.com/sirinsidiator/ESO-LibHistoire/assets/43454462/dda35432-9a50-48cc-8f87-da1733cb4c9e)

Here is the Guild history when clicking the link.
![image](https://github.com/sirinsidiator/ESO-LibHistoire/assets/43454462/dcb683fc-76ed-43dd-a4fb-8f505001deb2)

**Comment by sirinsidiator** [comment]
These are bugs in the new history and there is nothing I can do on my end to fix it.

**Comment by johnbnstx** [comment]
Thank you for the quick reply. Should I open the case with ESO for the history, or you would probably have a better way to state it. If you can tell me the bug description I can help open the case from my end.

**Comment by sirinsidiator** [comment]
The best course of action would be to use the ingame /bug command and report it there. More user reporting this as a problem means more priority for it getting fixed.
