### ISSUE TITLE
Sync failing after a few hours.

### ISSUE THREAD

**Issue by johnbnstx** [sirinsidiator/ESO-LibHistoire#5]
Did the latest update from LibHistoire and Master Merchant, but still having issues.

My day job is troubleshooting stuff. I am on vacation this week. if you want somebody to help debug I will volunteer. I use Master Merchant that uses LibHistoire. I have a primary account and a secondary account.

What I have seen is the secondary has 1 different guild and it has issues syncing the game history to MM. if I clear the cache and reload everything on the primary account it seems to work for a few hours and then loses the link.

This time logs popped up.
user:/AddOns/LibAsync/LibAsync.lua:299: operator < is not supported for number < nil
stack traceback:
user:/AddOns/LibAsync/LibAsync.lua:299: in function 'asyncForWithStep'
	<Locals> self = [table:1]{lastCallIndex = 1, name = "LibHistoire2"}, func = user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryProcessingRequest.lua:50, index = 2, step = -1 </Locals>
user:/AddOns/LibAsync/LibAsync.lua:327: in function 'task:Do'
	<Locals> self = [table:1], func = user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryProcessingRequest.lua:50, callstackIndex = 1, shouldBeFalse = F, p1 = 2, p3 = -1 </Locals>
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryProcessingRequest.lua:50: in function 'GuildHistoryProcessingRequest:StartProcessing'
	<Locals> self = [table:2]{currentIndex = 2}, endId = 95039851, listener = [table:3]{running = F, stopOnLastEvent = T, afterEventTime = 1710400720}, startId = 95033747, startIndex = 2 </Locals>
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryCacheCategory.lua:387: in function 'GuildHistoryCacheCategory:ProcessNextRequest'
	<Locals> self = [table:4]{progressDirty = T, key = "NA Megaserver/592467/3", unprocessedEventsStartTime = 1710400720, rangeInfoDirty = F, guildId = 592467, category = 3}, request = [table:2] </Locals>
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryCacheCategory.lua:363: in function 'GuildHistoryCacheCategory:QueueProcessingRequest'
	<Locals> self = [table:4], request = [table:2] </Locals>
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryEventListener.lua:201: in function 'GuildHistoryEventListener:Start'
	<Locals> self = [table:3] </Locals>
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryLegacyEventListener.lua:340: in function 'GuildHistoryLegacyEventListener:Start'
	<Locals> self = [table:5]{eventsLeft = 0, key = "NA Megaserver/592467/3", afterEventTime = 1710400720, iterationCompletedCount = 0, guildId = 592467, legacyCategory = 3}, _ = 1, listener = [table:3] </Locals>
user:/AddOns/MasterMerchant/Libs/LibGuildStore/LGS_LibHistoire.lua:142: in function 'internal:SetupListener'
	<Locals> self = [table:6]{itemLinksCount = 305327, GS_CHECK_ACCOUNTNAME = "accountNames", sr_index_count = 15489420, nameFilterNamespace = "namefilterna", GS_EU_LISTING_NAMESPACE = "listingseu", GS_EU_NAMESPACE = "dataeu", GS_EU_GUILD_LIST_NAMESPACE = "currentEUGuilds", GS_EU_NAME_FILTER_NAMESPACE = "namefiltereu", totalCanceled = 3249, cr_index_count = 39040, GS_NA_VISIT_TRADERS_NAMESPACE = "visitedNATraders", pricingNamespace = "pricingdatana", dataNamespace = "datana", GS_ALL_PRICING_NAMESPACE = "pricingdataall", totalPurchases = 30285, verboseLevel = 4, visitedNamespace = "visitedNATraders", guildNamesCount = 508, supported_lang = T, libHistoireNamespace = "libhistoirena", effective_lang = "en", GS_NA_LIBHISTOIRE_NAMESPACE = "libhistoirena", GS_NA_PURCHASE_NAMESPACE = "purchasena", guildListNamespace = "currentNAGuilds", GS_NA_FIRST_RUN_NAMESPACE = "firstRunNa", GS_EU_POSTED_NAMESPACE = "posteditemseu", GS_EU_VISIT_TRADERS_NAMESPACE = "visitedEUTraders", postedNamespace = "posteditemsna", pir_index_count = 193460, totalSales = 1068827, GS_CHECK_ITEMLINK = "itemLink", GS_EU_LIBHISTOIRE_NAMESPACE = "libhistoireeu", GS_EU_PURCHASE_NAMESPACE = "purchaseeu", NON_GUILD_MEMBER_PURCHASE = 0, listingsNamespace = "listingsna", isDatabaseBusy = F, lr_index_count = 269675, GS_NA_CANCELLED_NAMESPACE = "cancelleditemsna", GS_CHECK_GUILDNAME = "guildNames", firstrunNamespace = "firstRunNa", GS_NA_PRICING_NAMESPACE = "pricingdatana", cancelledNamespace = "cancelleditemsna", IMPORTED_PURCHASE = 2, GS_NA_LISTING_NAMESPACE = "listingsna", totalListings = 20117, GS_NA_NAME_FILTER_NAMESPACE = "namefilterna", purchasesNamespace = "purchasena", totalPosted = 15985, GS_NA_POSTED_NAMESPACE = "posteditemsna", GUILD_MEMBER_PURCHASE = 1}, guildId = 592467, newestTimestamp = 1710400720, newestEventID = 3095039851 </Locals>
user:/AddOns/MasterMerchant/Libs/LibGuildStore/LGS_LibHistoire.lua:226: in function 'func'
/EsoUI/Libraries/Globals/globalapi.lua:263: in function '(anonymous)'

**Comment by sirinsidiator** [comment]
The best way you could help right now is to send me a full LibDebugLogger log from the moment the error occurs (https://www.esoui.com/portal.php?&id=218&pageid=68). If you don't feel comfortable posting the link publicly, you can send me a pm on esoui or just mail it to my github email.

**Comment by johnbnstx** [comment]
It will not let me into private messages with ESOUI.  How do I mail to github email? according to instructions it says should be on the left hand side of your profile. but nothing is there. Sorry have never done the github email or PM on ESOUI.

**Comment by johnbnstx** [comment]
I have disabled Libhistoire, MM, and ATT on my alt that this computer jumps to. Also purged all history direct from the folder. So far I am not seeing the error again. Once I get all the updated history done and populated to MM/ATT I will save backup and put it on my other computer to do testing to see if the error occurs, which I am pretty certain it will. I think it is because with the alt it is getting a separate history file and somehow that is screwing up libhistorie. I have the file from before but I tried to find how to email you or DM, but I do not have DM privileges on ESOUI, and I am not seeing an email link on github.

**Comment by johnbnstx** [comment]
Copying over all the files, INCLUDING ESO history, and when brought up on the laptop it zeroes the history files on the other computer. Although MM is probably retaining the data from the Saved History folder file "GS##Data.lua" and ATT is retaining from theirs from "ArkadiusTradeToolsSalesData##.lua".

But if I create another account and use this same computer to run the account it will create a new instance of History and that is when LibHistoire starts to flake out.
This also holds true if I switch to another computer, even if I have taken a backup of LibHistoire and all the files to the new computer. MM/ATT no longer updates because LibHistoire is looking for a file that may have changed. I had sold 2 items in 2 different guilds.

When on my Laptop after about 30 minutes of being online I quit the program and then restarted. it then showed only ONE of the two sales, even after about 15-20 minutes.

This is a bad ZOS mistake. if my machine crashes or is unavailable, I would have to rebuild the entire history file again? ouch.

**Comment by johnbnstx** [comment]
I just logged back into my main computer on my main account. after a few minutes it detected the one sale in the one guild almost immediately and then the other sale a few minutes later.

You have done a fantastic job working around ZOS mess of a history. But how do we handle having 2 different accounts that have most traders the same, but may have a different trader than the main? handle it by not having the history flake.

**Comment by sirinsidiator** [comment]
If you do not have permission to send pms on ESOUI, you may not have confirmed your account yet. You should have received an email with an activation link. Maybe it landed in the spam?
As for the github email, you are right. Seems others cannot see that anymore. You could check out the repository locally and then you should be able to see it in the commit log though.

As for the cache file not being reused between accounts and machines, that sounds like a bug. It should be possible to copy and reuse the files as far as I am aware and I do see some people who claim it works, while others say it doesn't.

**Comment by johnbnstx** [comment]
Junk mail!  thank you for reminding me on that!! the ESOUI page was able to refresh showing MM and LibHistoire both with updates. I will load both of those. get to full history and then test again.

**Comment by johnbnstx** [comment]
closing this old one as 2 updates have occurred. starting clean one.
