### ISSUE TITLE
Logging from primary to alternate then back to primary on the same computer generates error.

### ISSUE THREAD

**Issue by johnbnstx** [sirinsidiator/ESO-LibHistoire#6]
Logging from primary to alternate then back to primary on the same computer generates error.

2.0.4 works really well on my main account. Logged into Alt account in with correct addon's re-enabled. Everything appeared to work. I did have to go to Guild history and click just once for each of the shared guilds. the one guild that was not shared had to extract all history as expected.

Only ONE Guild did not want to continue pulling history, I believe that is a ZoS problem, but do not know.

assert: newestTime must be greater or equal to oldestTime
stack traceback:
[C]: in function 'assert'
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryAdapter.lua:89: in function 'GuildHistoryAdapter:GetGuildHistoryEventIndicesForTimeRange'
	<Locals> self = [table:1]{}, guildId = 303181, category = 3, newestTime = 86701589, oldestTime = 1710517048 </Locals>
user:/AddOns/LibHistoire/guildHistoryCache/compatibility.lua:293: in function 'ZO_GuildHistoryEventCategoryData:GetEventsInTimeRange'
	<Locals> self = [table:2]{eventCategory = 3}, newestTimeS = 86701589, oldestTimeS = 1710517048 </Locals>
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryCacheCategory.lua:454: in function 'GuildHistoryCacheCategory:StartProcessingEvents'
	<Locals> self = [table:3]{key = "NA Megaserver/303181/3", unprocessedEventsStartTime = 1710517048, guildId = 303181, progressDirty = T, category = 3, rangeInfoDirty = F}, newestLinkedEventId = 95817083, oldestLinkedEventId = 1709322949, guildId = 303181, category = 3, rangeIndex = 2, newestTime = 1710517330, oldestTime = 1710517048, newestEventId = 95819231, oldestEventId = 95817083, unlinkedEvents = [table:4]{}, missedEvents = [table:5]{}, categoryData = [table:2], _ = 1709322949, oldestLinkedEventTime = 86701589 </Locals>
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryCacheCategory.lua:348: in function 'GuildHistoryCacheCategory:OnCategoryUpdated'
	<Locals> self = [table:3], flags = 3, guildId = 303181, category = 3, oldestLinkedEventId = 1709322949, newestLinkedEventId = 95817083 </Locals>
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryCache.lua:40: in function 'callback'
	<Locals> categoryData = [table:2], flags = 3, guildId = 303181, category = 3, categoryCache = [table:3] </Locals>
/EsoUI/Libraries/Utility/ZO_CallbackObject.lua:132: in function 'ZO_CallbackObjectMixin:FireCallbacks'
	<Locals> self = [table:6]{fireCallbackDepth = 1}, eventName = "CategoryUpdated", registry = [table:7]{}, callbackInfoIndex = 1, callbackInfo = [table:8]{4 = F}, callback = user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryCache.lua:36, deleted = F </Locals>
/EsoUI/Ingame/GuildHistory/GuildHistory_Manager.lua:159: in function 'ZO_GuildHistory_Manager:OnCategoryUpdated'
	<Locals> self = [table:6], guildId = 303181, eventCategory = 3, flags = 3, guildData = [table:9]{guildId = 303181}, categoryData = [table:2] </Locals>
/EsoUI/Ingame/GuildHistory/GuildHistory_Manager.lua:150: in function '(anonymous)'
	<Locals> _ = 131831 </Locals>
user:/AddOns/LibAsync/LibAsync.lua:299: operator < is not supported for number < nil
stack traceback:
user:/AddOns/LibAsync/LibAsync.lua:299: in function 'asyncForWithStep'
	<Locals> self = [table:1]{name = "LibHistoire2", lastCallIndex = 1}, func = user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryProcessingRequest.lua:50, index = 7, step = -1 </Locals>
user:/AddOns/LibAsync/LibAsync.lua:327: in function 'task:Do'
	<Locals> self = [table:1], func = user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryProcessingRequest.lua:50, callstackIndex = 1, shouldBeFalse = F, p1 = 7, p3 = -1 </Locals>
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryProcessingRequest.lua:50: in function 'GuildHistoryProcessingRequest:StartProcessing'
	<Locals> self = [table:2]{currentIndex = 7}, endId = 95817409, listener = [table:3]{afterEventTime = 1710517081, stopOnLastEvent = T, running = F}, startId = 95789957, startIndex = 7 </Locals>
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryCacheCategory.lua:425: in function 'GuildHistoryCacheCategory:ProcessNextRequest'
	<Locals> self = [table:4]{key = "NA Megaserver/592467/3", unprocessedEventsStartTime = 1710517081, guildId = 592467, progressDirty = T, category = 3, rangeInfoDirty = F}, request = [table:2] </Locals>
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryCacheCategory.lua:401: in function 'GuildHistoryCacheCategory:QueueProcessingRequest'
	<Locals> self = [table:4], request = [table:2] </Locals>
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryEventListener.lua:201: in function 'GuildHistoryEventListener:Start'
	<Locals> self = [table:3] </Locals>
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryLegacyEventListener.lua:340: in function 'GuildHistoryLegacyEventListener:Start'
	<Locals> self = [table:5]{afterEventTime = 1710517081, key = "NA Megaserver/592467/3", eventsLeft = 0, iterationCompletedCount = 0, legacyCategory = 3, guildId = 592467}, _ = 1, listener = [table:3] </Locals>
user:/AddOns/MasterMerchant/Libs/LibGuildStore/LGS_LibHistoire.lua:142: in function 'internal:SetupListener'
	<Locals> self = [table:6]{visitedNamespace = "visitedNATraders", GS_EU_NAMESPACE = "dataeu", GS_CHECK_ITEMLINK = "itemLink", GS_NA_VISIT_TRADERS_NAMESPACE = "visitedNATraders", GS_NA_FIRST_RUN_NAMESPACE = "firstRunNa", accountNamesCount = 126726, GS_EU_PURCHASE_NAMESPACE = "purchaseeu", pr_index_count = 359203, pricingNamespace = "pricingdatana", purchasesNamespace = "purchasena", viewer = F, GS_NA_LIBHISTOIRE_NAMESPACE = "libhistoirena", GS_NA_POSTED_NAMESPACE = "posteditemsna", totalPosted = 16022, listingsNamespace = "listingsna", postedNamespace = "posteditemsna", GS_EU_POSTED_NAMESPACE = "posteditemseu", GS_EU_NAME_FILTER_NAMESPACE = "namefiltereu", GS_NA_CANCELLED_NAMESPACE = "cancelleditemsna", lr_index_count = 131721, totalListings = 10203, GS_EU_FIRST_RUN_NAMESPACE = "firstRunEu", guildListNamespace = "currentNAGuilds", cr_index_count = 39451, NON_GUILD_MEMBER_PURCHASE = 0, PlayerSpecialText = "hfdkkdfunlajjamdhsiwsuwj", GS_NA_PRICING_NAMESPACE = "pricingdatana", sr_index_count = 15549381, GUILD_MEMBER_PURCHASE = 1, GS_EU_PRICING_NAMESPACE = "pricingdataeu", GS_ALL_PRICING_NAMESPACE = "pricingdataall", supported_lang = T, effective_lang = "en", guildNamesCount = 509, client_lang = "en", GS_EU_GUILD_LIST_NAMESPACE = "currentEUGuilds", itemLinksCount = 306467, verboseLevel = 4, guildList = "Mammoth Trading Company, The N...", totalPurchases = 30319, GS_NA_PURCHASE_NAMESPACE = "purchasena", libHistoireNamespace = "libhistoirena", GS_EU_LISTING_NAMESPACE = "listingseu", GS_NA_LISTING_NAMESPACE = "listingsna", GS_NA_NAMESPACE = "datana", GS_EU_VISIT_TRADERS_NAMESPACE = "visitedEUTraders", GS_EU_CANCELLED_NAMESPACE = "cancelleditemseu", totalSales = 1072765, pir_index_count = 193908, GS_EU_LIBHISTOIRE_NAMESPACE = "libhistoireeu"}, guildId = 592467, newestTimestamp = 1710517081, newestEventID = 3095817409 </Locals>
user:/AddOns/MasterMerchant/Libs/LibGuildStore/LGS_LibHistoire.lua:226: in function 'func'
/EsoUI/Libraries/Globals/globalapi.lua:263: in function '(anonymous)'

**Comment by johnbnstx** [comment]
Reload UI wait few minutes and get this again. 

Have sent you the debug through DM.

assert: newestTime must be greater or equal to oldestTime
stack traceback:
[C]: in function 'assert'
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryAdapter.lua:89: in function 'GuildHistoryAdapter:GetGuildHistoryEventIndicesForTimeRange'
	<Locals> self = [table:1]{}, guildId = 303181, category = 3, newestTime = 86701589, oldestTime = 1710517048 </Locals>
user:/AddOns/LibHistoire/guildHistoryCache/compatibility.lua:293: in function 'ZO_GuildHistoryEventCategoryData:GetEventsInTimeRange'
	<Locals> self = [table:2]{eventCategory = 3}, newestTimeS = 86701589, oldestTimeS = 1710517048 </Locals>
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryCacheCategory.lua:454: in function 'GuildHistoryCacheCategory:StartProcessingEvents'
	<Locals> self = [table:3]{key = "NA Megaserver/303181/3", unprocessedEventsStartTime = 1710517048, category = 3, rangeInfoDirty = F, progressDirty = T, guildId = 303181}, newestLinkedEventId = 95817083, oldestLinkedEventId = 1709322949, guildId = 303181, category = 3, rangeIndex = 2, newestTime = 1710517704, oldestTime = 1710517048, newestEventId = 95822677, oldestEventId = 95817083, unlinkedEvents = [table:4]{}, missedEvents = [table:5]{}, categoryData = [table:2], _ = 1709322949, oldestLinkedEventTime = 86701589 </Locals>
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryCacheCategory.lua:348: in function 'GuildHistoryCacheCategory:OnCategoryUpdated'
	<Locals> self = [table:3], flags = 2, guildId = 303181, category = 3, oldestLinkedEventId = 1709322949, newestLinkedEventId = 95817083 </Locals>
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryCache.lua:40: in function 'callback'
	<Locals> categoryData = [table:2], flags = 2, guildId = 303181, category = 3, categoryCache = [table:3] </Locals>
/EsoUI/Libraries/Utility/ZO_CallbackObject.lua:132: in function 'ZO_CallbackObjectMixin:FireCallbacks'
	<Locals> self = [table:6]{fireCallbackDepth = 1}, eventName = "CategoryUpdated", registry = [table:7]{}, callbackInfoIndex = 1, callbackInfo = [table:8]{4 = F}, callback = user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryCache.lua:36, deleted = F </Locals>
/EsoUI/Ingame/GuildHistory/GuildHistory_Manager.lua:159: in function 'ZO_GuildHistory_Manager:OnCategoryUpdated'
	<Locals> self = [table:6], guildId = 303181, eventCategory = 3, flags = 2, guildData = [table:9]{guildId = 303181}, categoryData = [table:2] </Locals>
/EsoUI/Ingame/GuildHistory/GuildHistory_Manager.lua:150: in function '(anonymous)'
	<Locals> _ = 131831 </Locals>
user:/AddOns/LibAsync/LibAsync.lua:299: operator < is not supported for number < nil
stack traceback:
user:/AddOns/LibAsync/LibAsync.lua:299: in function 'asyncForWithStep'
	<Locals> self = [table:1]{name = "LibHistoire6", lastCallIndex = 1}, func = user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryProcessingRequest.lua:50, index = 54, step = -1 </Locals>
user:/AddOns/LibAsync/LibAsync.lua:327: in function 'task:Do'
	<Locals> self = [table:1], func = user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryProcessingRequest.lua:50, callstackIndex = 1, shouldBeFalse = F, p1 = 54, p3 = -1 </Locals>
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryProcessingRequest.lua:50: in function 'GuildHistoryProcessingRequest:StartProcessing'
	<Locals> self = [table:2]{currentIndex = 54}, endId = 95817719, listener = [table:3]{running = F, afterEventTime = 1710517129, stopOnLastEvent = T}, startId = 95793771, startIndex = 54 </Locals>
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryCacheCategory.lua:425: in function 'GuildHistoryCacheCategory:ProcessNextRequest'
	<Locals> self = [table:4]{key = "NA Megaserver/639371/3", unprocessedEventsStartTime = 1710517129, category = 3, rangeInfoDirty = T, progressDirty = T, guildId = 639371}, request = [table:2] </Locals>
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryCacheCategory.lua:401: in function 'GuildHistoryCacheCategory:QueueProcessingRequest'
	<Locals> self = [table:4], request = [table:2] </Locals>
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryEventListener.lua:201: in function 'GuildHistoryEventListener:Start'
	<Locals> self = [table:3] </Locals>
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryLegacyEventListener.lua:340: in function 'GuildHistoryLegacyEventListener:Start'
	<Locals> self = [table:5]{key = "NA Megaserver/639371/3", legacyCategory = 3, eventsLeft = 0, afterEventTime = 1710517129, iterationCompletedCount = 0, guildId = 639371}, _ = 1, listener = [table:3] </Locals>
user:/AddOns/MasterMerchant/Libs/LibGuildStore/LGS_LibHistoire.lua:142: in function 'internal:SetupListener'
	<Locals> self = [table:6]{guildList = "Mammoth Trading Company, The N...", GS_NA_NAMESPACE = "datana", cancelledNamespace = "cancelleditemsna", GS_EU_FIRST_RUN_NAMESPACE = "firstRunEu", totalListings = 10203, GUILD_MEMBER_PURCHASE = 1, GS_NA_GUILD_LIST_NAMESPACE = "currentNAGuilds", GS_NA_CANCELLED_NAMESPACE = "cancelleditemsna", GS_EU_LIBHISTOIRE_NAMESPACE = "libhistoireeu", client_lang = "en", viewer = F, GS_EU_PURCHASE_NAMESPACE = "purchaseeu", GS_EU_NAMESPACE = "dataeu", GS_CHECK_ITEMLINK = "itemLink", GS_NA_PRICING_NAMESPACE = "pricingdatana", effective_lang = "en", IMPORTED_PURCHASE = 2, guildListNamespace = "currentNAGuilds", GS_CHECK_GUILDNAME = "guildNames", totalPurchases = 30319, lr_index_count = 131721, guildNamesCount = 509, GS_EU_GUILD_LIST_NAMESPACE = "currentEUGuilds", GS_EU_CANCELLED_NAMESPACE = "cancelleditemseu", GS_NA_LIBHISTOIRE_NAMESPACE = "libhistoirena", GS_NA_FIRST_RUN_NAMESPACE = "firstRunNa", totalPosted = 16022, GS_NA_PURCHASE_NAMESPACE = "purchasena", PlayerSpecialText = "hfdkkdfunlajjamdhsiwsuwj", GS_EU_PRICING_NAMESPACE = "pricingdataeu", GS_CHECK_ACCOUNTNAME = "accountNames", libHistoireNamespace = "libhistoirena", visitedNamespace = "visitedNATraders", firstrunNamespace = "firstRunNa", nameFilterNamespace = "namefilterna", isDatabaseBusy = F, purchasesNamespace = "purchasena", dataNamespace = "datana", supported_lang = T, GS_EU_NAME_FILTER_NAMESPACE = "namefiltereu", cr_index_count = 39451, GS_NA_POSTED_NAMESPACE = "posteditemsna", GS_EU_LISTING_NAMESPACE = "listingseu", NON_GUILD_MEMBER_PURCHASE = 0, listingsNamespace = "listingsna", pir_index_count = 193908, totalCanceled = 3285, pricingNamespace = "pricingdatana", totalSales = 1072802, GS_EU_POSTED_NAMESPACE = "posteditemseu"}, guildId = 639371, newestTimestamp = 1710517129, newestEventID = 3095817719 </Locals>
user:/AddOns/MasterMerchant/Libs/LibGuildStore/LGS_LibHistoire.lua:226: in function 'originalFunc'
user:/AddOns/LibDebugLogger/Initialization.lua:240: in function 'func'
/EsoUI/Libraries/Globals/globalapi.lua:263: in function '(anonymous)'

**Comment by johnbnstx** [comment]
had 4 sold items yet none showed up in MM or ATT. when I looked at history it says "no listeners"??? Not sure if it had been like that since I had switched between alt and main or not.

![image](https://github.com/sirinsidiator/ESO-LibHistoire/assets/43454462/0cf51b7e-f011-40ab-b7af-0839c63adb65)

**Comment by sirinsidiator** [comment]
As I mentioned in the PM, switching between accounts is currently not working as intended. I need to update the library first. Otherwise it will end up throwing errors or doing what you see there.

**Comment by johnbnstx** [comment]
Oh I am sorry, I had missed that!!

Is there any log info that I can get you?

**Comment by sirinsidiator** [comment]
Not right now, but once I have fixed the root cause, I'll need you to test it for me, since I don't have multiple accounts.

**Comment by johnbnstx** [comment]
no problem. Well I was able to reset link and reloadui. MM is now updating and I guess that is the listener that is working, as it says only 1 listener.

**Comment by johnbnstx** [comment]
OK Found that if I purge the history through \AppData\Local\Elder Scrolls Online\live\CachedData\GuildHistory. the errors stop and you can then sync properly.

**Comment by johnbnstx** [comment]
version 2.0.6 I can switch back and forth between accounts now without errors. But I seem to get a heavy delay in update. It keeps saying "Waiting for request to be sent". Do not know if this is ZoS or not. Last night I did not have that issue and I was on 2.0.5. 

I even tried to delete cache and reloadui. that seemed to help some guild not others though.

![image](https://github.com/sirinsidiator/ESO-LibHistoire/assets/43454462/59b873bb-a7ab-4ecd-aabd-d3585a08b6dc)

Even waiting for a long time there is 1 guild that just cannot update.
![image](https://github.com/sirinsidiator/ESO-LibHistoire/assets/43454462/59deb213-153a-4f41-8099-c7b3621b4c58)

**Comment by sirinsidiator** [comment]
Version 2.0.7 will take care of the issue in the first screen. The second one is unfortunately a game bug and we will have to wait for ZOS to fix it. The only way to get past that is to either restore a backup of the cache file, or reset the cache entirely.

**Comment by johnbnstx** [comment]
2.0.7 is perfect!!! I was able to switch back and forth to the laptop and to the alt accounts.

Only problem I have is history gets stuck still, as noted above that sometimes there is no listeners or 1 listener and not 2. either have to reloadui, press E on history, reset link, or switch accounts for the information to update correctly. But I think that is ZoS.

Thank you for your hard work.

**Comment by johnbnstx** [comment]
2.0.7 is perfect!!! I was able to switch back and forth to the laptop and to the alt accounts.

Only problem I have is history gets stuck still, as noted above that sometimes there is no listeners or 1 listener and not 2. either have to reloadui, press E on history, reset link, or switch accounts for the information to update correctly. But I think that is ZoS.

Thank you for your hard work.
