### ISSUE TITLE
"History has not linked to stored events yet" lag, multi-colors...

### ISSUE THREAD

**Issue by Mord88** [sirinsidiator/ESO-LibHistoire#7]
Evening,

I reinstalled the game and my addons after update 41 for ESO. I cannot say for sure this is a U41 issue as I had personal troubles with OneDrive (long story, I'm no longer using it). 

In short, the library will not sync. I cannot see my history, etc. I'm a little surprised reinstalling the game and the addons did not fix this. I'm okay with losing all my sales data if it fixes this moving forward.
![Capture](https://github.com/sirinsidiator/ESO-LibHistoire/assets/163706163/1e1ca2d6-de21-4bf2-9586-5b963b0e653e)

**Comment by sirinsidiator** [comment]
You are not using the most current version of the library. I've added a version label to the bottom right corner of the status window in 2.0.6, so your version is at least one older than that.
I've also just uploaded 2.0.7 and it is currently waiting for approval, so please try again with that version once it is available for download.

**Comment by Mord88** [comment]
Evening, 
Thank you for taking the time this morning. I have updated the version and receiving the message "Waiting for request to be sent". See image attached. 
![Capture](https://github.com/sirinsidiator/ESO-LibHistoire/assets/163706163/e3ac44bf-1b66-4329-ad6c-a587c16616d6)
